services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: datosinter
      MYSQL_USER: dwdmcisco1
      MYSQL_PASSWORD: dwdmspan1
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      # Ejecutar init.sql para crear tabla spans
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    # healthcheck removed: backend waits via netcat

  backend:
    build:
      context: ./backend
    ports:
      - '3001:3001'
    environment:
      DB_HOST: db
      DB_USER: dwdmcisco1
      DB_PASSWORD: dwdmspan1
      DB_NAME: datosinter
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    depends_on:
      - db

  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      # En Docker Compose, usar el nombre de servicio 'backend'
      VITE_API_URL: http://backend:3001
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'admin'
      GF_USERS_ALLOW_SIGN_UP: 'false'
      GF_INSTALL_PLUGINS: 'grafana-piechart-panel,grafana-worldmap-panel'
      GF_DEFAULT_APP_HOME_DASHBOARD_PATH: '/var/lib/grafana/dashboards'

volumes:
  db_data:
  grafana_data:
